# Generated by Django 5.0.7 on 2024-12-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('group_capacity', models.IntegerField(verbose_name='Вместимость группы')),
                ('group_is_raining', models.BooleanField(default=False, verbose_name='Группа на обучении')),
                ('admission_to_test', models.BooleanField(default=False, verbose_name='Группа допущена к тестам')),
                ('admission_to_exam', models.BooleanField(default=False, verbose_name='Группа допущена к экзамену')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.studentgroup'),
        ),
    ]
