# Generated by Django 5.0.7 on 2024-09-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerprofile',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
